### ISSUE TITLE
NoClassDefFoundError for DumpProcessor

### ISSUE THREAD

**Issue by StrangeTcy** [epfl-lts2/sparkwiki#23]
Running `spark-submit --class ch.epfl.lts2.wikipedia.DumpProcessor --master 'local[*]' --executor-memory 16g --driver-memory 16g --packages org.rogach:scallop_2.11:4.0.1 sparkwiki/target/scala-2.11/sparkwiki_2.11-0.13.0.jar --dumpPath /mnt/data/wikipedia/dumps --outputPath /mnt/data/wikipedia/dumps-pre-processed/  --namePrefix enwiki-20210722
` on Ubuntu after building the jar file with `sbt package`
results in the following error:
```
Exception in thread "main" java.lang.NoClassDefFoundError: scala/Product$class
        at org.rogach.scallop.Scallop.<init>(Scallop.scala:63)
        at org.rogach.scallop.Scallop$.apply(Scallop.scala:13)
        at org.rogach.scallop.ScallopConfBase.<init>(ScallopConfBase.scala:55)
        at org.rogach.scallop.ScallopConf.<init>(ScallopConf.scala:9)
        at ch.epfl.lts2.wikipedia.ProcessorConf.<init>(DumpProcessor.scala:10)
        at ch.epfl.lts2.wikipedia.DumpProcessor$.main(DumpProcessor.scala:81)
        at ch.epfl.lts2.wikipedia.DumpProcessor.main(DumpProcessor.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:951)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1039)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1048)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: scala.Product$class
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 19 more

```

It'd seem that something didn't get compiled properly during jar file building, but I'm no Java/Scala expert.

**Comment by naspert** [comment]
Hm not sure this is entirely your fault. Which version of Scala/Ubuntu are you running ?

**Comment by stetelepta** [comment]
I had the same error, I used the spark-submit example in the [detailed deployment tutorial](https://github.com/epfl-lts2/sparkwiki/blob/master/helpers/README.md) (3.1 Pre-process files) which still uses the old scallop 2.11 version. When changing this to `org.rogach:scallop_2.12:4.0.1` it works for me.

**Comment by naspert** [comment]
thanks for the update.
